### ISSUE TITLE
Regular user feeds 404

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/byline-manager#126] opened 2023-07-10 14:59 UTC
### Description of the bug

Currently, the plugin is removing the author rewrite rules, including support for the feed of regular authors in favor of the Byline profile feed.

https://github.com/alleyinteractive/byline-manager/blob/eb1b409f6eabfaa276fa59a191be479108eca83d/inc/core-filters.php#L83

This creates a regression where regular authors, which had feeds, lose their feed. And even if the user is linked to a profile, their legacy posts are not ported over to the new feed page (profile feed).

I'd recommend keeping the author feeds.

### Steps To Reproduce

1. Site already have authors with posts.
2. Add Byline Manager
3. The feed page for regular `WP_User`(s) 404s: `http://site/author/user_slug/feed/`

**Comment by kevinfodness** [comment] 2024-10-16 18:31
This behavior is by design. Byline Manager replaces all aspects of authorship on the front-end, and Byline Manager author feeds should be used instead of normal WordPress user feeds. If you are adopting Byline Manager and want to have the URLs be the same, match the author slug from the user to the Byline Manager Profile. However, there is currently a bug #33 where the feeds for profiles do not contain posts authored by those profiles, which does need to be fixed, but I will close this issue in favor of that one.

**Closed as completed by kevinfodness** 2024-10-16 18:31 UTC
Labels: wontfix

**Comment by renatonascalves** [comment] 2024-10-17 01:45
> If you are adopting Byline Manager and want to have the URLs be the same, match the author slug from the user to the Byline Manager Profile. 

The use case at the time was that not all authors needed to have byline profiles. So those legacy authors posts/pages were gone. It does sort of force a site to choose where, for business reasons, they might not want to.

**Comment by kevinfodness** [comment] 2024-10-17 12:20
At a core plugin level, it's designed to (and should remain designed to) fully take over the author experience as far as users are concerned. If individual sites want to support a hybrid model, they can do that using custom code.
